In [1]:
#加载数据
import pandas as pd
import numpy as np
data = pd.read_csv('task2_data.csv')
data.head()

score  school  award  gender  english  y
0      0       1      0       1        1  0
1      1       0      0       0        0  0
2      0       1      1       0        1  1
3      1       1      0       1        0  1
4      0       0      0       1        0  0

In [2]:
#X y 赋值
X = data.drop(['y'],axis=1)
y = data.loc[:,'y']
X.head()
y.head()
print(X.shape,y.shape)

(300, 5) (300,)


In [3]:
#创建朴素贝叶斯模型并训练
from sklearn.naive_bayes import CategoricalNB
model = CategoricalNB()
#模型训练
model.fit(X,y)

CategoricalNB()

In [4]:
#训练数据的概率预测
y_predict_prob = model.predict_proba(X)
print(y_predict_prob)

[[0.72279958 0.21735277 0.05984765]
 [0.79655931 0.16840549 0.0350352 ]
 [0.37146649 0.40763466 0.22089885]
 [0.70511475 0.23857787 0.05630738]
 [0.88207671 0.09877993 0.01914336]
 [0.38753488 0.44680162 0.1656635 ]
 [0.29570921 0.41950319 0.2847876 ]
 [0.40311169 0.3656524  0.23123591]
 [0.76275476 0.19963483 0.03761041]
 [0.62733509 0.30997504 0.06268987]
 [0.65330689 0.2100501  0.13664301]
 [0.63959653 0.23138479 0.12901867]
 [0.81070146 0.1523267  0.03697185]
 [0.71204998 0.19926005 0.08868997]
 [0.65666737 0.255277   0.08805563]
 [0.83984452 0.13734665 0.02280883]
 [0.85828977 0.11043131 0.03127893]
 [0.88207671 0.09877993 0.01914336]
 [0.51625575 0.3376476  0.14609665]
 [0.71204998 0.19926005 0.08868997]
 [0.83984452 0.13734665 0.02280883]
 [0.65666737 0.255277   0.08805563]
 [0.88207671 0.09877993 0.01914336]
 [0.35609249 0.43968063 0.20422688]
 [0.6391688  0.26120538 0.09962582]
 [0.84751623 0.12269571 0.02978806]
 [0.85828977 0.11043131 0.03127893]
 [0.88207671 0.09877993 0.01

In [5]:
#训练的预测
y_predict = model.predict(X)
print(y_predict)

[0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 2 0 2 0
 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 1 0 0 2 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0
 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 2 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 2 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 1 0
 0 0 0 0]


In [6]:
#计算模型准确率
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y,y_predict)
print(accuracy)

0.6833333333333333


In [7]:
#测试样本预测
X_test = np.array([[2,1,1,1,1]])
y_test_predict_prob = model.predict_proba(X_test)
y_test_predict = model.predict(X_test)
print(y_test_predict)

[2]


In [8]:
#5个测试样本预测
X_test = np.array([[2,1,1,1,1],[2,1,1,1,0],[2,1,1,0,0],[2,1,0,0,0],[2,0,0,0,0]])
y_test_predict_prob = model.predict_proba(X_test)
y_test_predict = model.predict(X_test)

print(y_test_predict_prob)
print(y_test_predict)

[[0.15246575 0.34559122 0.50194304]
 [0.20270024 0.39989757 0.39740219]
 [0.15786683 0.45482276 0.38731042]
 [0.38753488 0.44680162 0.1656635 ]
 [0.59472319 0.29337952 0.11189729]]
[2 1 1 1 0]


In [9]:
#确认存储数据
print(X_test)
print(y_test_predict_prob)
print(y_test_predict)
print(X_test.shape,y_test_predict_prob.shape,y_test_predict.shape)

[[2 1 1 1 1]
 [2 1 1 1 0]
 [2 1 1 0 0]
 [2 1 0 0 0]
 [2 0 0 0 0]]
[[0.15246575 0.34559122 0.50194304]
 [0.20270024 0.39989757 0.39740219]
 [0.15786683 0.45482276 0.38731042]
 [0.38753488 0.44680162 0.1656635 ]
 [0.59472319 0.29337952 0.11189729]]
[2 1 1 1 0]
(5, 5) (5, 3) (5,)


In [10]:
#数据组合
test_data_result = np.concatenate((X_test,y_test_predict_prob,y_test_predict.reshape(5,1)),axis=1)
print(test_data_result)

[[2.         1.         1.         1.         1.         0.15246575
  0.34559122 0.50194304 2.        ]
 [2.         1.         1.         1.         0.         0.20270024
  0.39989757 0.39740219 1.        ]
 [2.         1.         1.         0.         0.         0.15786683
  0.45482276 0.38731042 1.        ]
 [2.         1.         0.         0.         0.         0.38753488
  0.44680162 0.1656635  1.        ]
 [2.         0.         0.         0.         0.         0.59472319
  0.29337952 0.11189729 0.        ]]


In [11]:
#格式转化
test_data_result = pd.DataFrame(test_data_result)
test_data_result.head()

0    1    2    3    4         5         6         7    8
0  2.0  1.0  1.0  1.0  1.0  0.152466  0.345591  0.501943  2.0
1  2.0  1.0  1.0  1.0  0.0  0.202700  0.399898  0.397402  1.0
2  2.0  1.0  1.0  0.0  0.0  0.157867  0.454823  0.387310  1.0
3  2.0  1.0  0.0  0.0  0.0  0.387535  0.446802  0.165663  1.0
4  2.0  0.0  0.0  0.0  0.0  0.594723  0.293380  0.111897  0.0

In [12]:
#列名称替换
test_data_result.columns = ['score','school','award','gender','english','p0','p1','p2','y_test_predict']
test_data_result.head()

score  school  award  gender  english        p0        p1        p2  \
0    2.0     1.0    1.0     1.0      1.0  0.152466  0.345591  0.501943   
1    2.0     1.0    1.0     1.0      0.0  0.202700  0.399898  0.397402   
2    2.0     1.0    1.0     0.0      0.0  0.157867  0.454823  0.387310   
3    2.0     1.0    0.0     0.0      0.0  0.387535  0.446802  0.165663   
4    2.0     0.0    0.0     0.0      0.0  0.594723  0.293380  0.111897   

   y_test_predict  
0             2.0  
1             1.0  
2             1.0  
3             1.0  
4             0.0

In [13]:
test_data_result.to_csv('test_data_result.csv')

![materials](materials2.png)